"""
Seed and update the PostgreSQL database with historical stock data from yfinance.

Reads tickers from data/tickers.json (generated by build_ticker_list.py).

Modes:
  - First run: downloads full history for all tickers
  - Subsequent runs: only fetches new data since each ticker's last date in the DB

Usage:
    python data/seed.py            # seed + update all tickers
    python data/seed.py AAPL MSFT  # seed/update specific tickers only
"""

import io
import json
import os
import sys
import time
from datetime import datetime, timedelta

import pandas as pd
import psycopg2
import yfinance as yf

DATABASE_URL = os.environ.get(
    "DATABASE_URL",
    "postgresql://quant:quant@localhost:5432/stocks",
)

DATA_DIR = os.path.dirname(__file__)
TICKERS_PATH = os.path.join(DATA_DIR, "tickers.json")
FAILED_LOG = os.path.join(DATA_DIR, "failed_tickers.json")

BATCH_SIZE = 100
DELAY_BETWEEN_BATCHES = 1.0


# ── Database helpers ─────────────────────────────────────────────


def get_last_dates(conn) -> dict[str, datetime]:
    """Get the most recent date per symbol in the database."""
    cur = conn.cursor()
    cur.execute("SELECT symbol, MAX(date) FROM prices GROUP BY symbol")
    result = {row[0]: row[1] for row in cur.fetchall()}
    cur.close()
    return result


def insert_rows(conn, df: pd.DataFrame):
    """Bulk-insert a DataFrame of price data using COPY."""
    if df.empty:
        return

    buf = io.StringIO()
    for _, row in df.iterrows():
        values = [
            row["symbol"],
            str(row["date"]),
            str(row.get("Open", "")),
            str(row.get("High", "")),
            str(row.get("Low", "")),
            str(row.get("Close", "")),
            str(row.get("Adj Close", "")),
            str(int(row["Volume"])) if pd.notna(row.get("Volume")) else "\\N",
            "\\N",  # dividend_amount
            "\\N",  # split_coefficient
        ]
        buf.write("\t".join(values) + "\n")

    buf.seek(0)
    cur = conn.cursor()
    cur.copy_from(
        buf,
        "prices",
        columns=(
            "symbol", "date", "open", "high", "low", "close",
            "adjusted_close", "volume", "dividend_amount", "split_coefficient",
        ),
    )
    conn.commit()
    cur.close()


# ── Download logic ───────────────────────────────────────────────


def download_batch(tickers: list[str], start: str = None) -> pd.DataFrame:
    """Download OHLCV data for a batch of tickers."""
    kwargs = {
        "tickers": tickers,
        "progress": False,
        "threads": True,
        "group_by": "ticker",
    }
    if start:
        kwargs["start"] = start
    else:
        kwargs["period"] = "max"

    return yf.download(**kwargs)


def extract_ticker_df(df: pd.DataFrame, ticker: str, batch_size: int) -> pd.DataFrame:
    """Pull a single ticker's data out of a multi-ticker download result."""
    if batch_size == 1:
        ticker_df = df.copy()
    else:
        if ticker not in df.columns.get_level_values(0):
            return pd.DataFrame()
        ticker_df = df[ticker].copy()

    ticker_df = ticker_df.dropna(subset=["Close"])
    if ticker_df.empty:
        return pd.DataFrame()

    ticker_df = ticker_df.reset_index()
    ticker_df["symbol"] = ticker

    # Normalize date column
    date_col = [c for c in ticker_df.columns if "date" in c.lower()]
    if date_col:
        ticker_df = ticker_df.rename(columns={date_col[0]: "date"})
    ticker_df["date"] = pd.to_datetime(ticker_df["date"]).dt.date

    return ticker_df


# ── Main ─────────────────────────────────────────────────────────


def seed():
    # Load ticker list
    if not os.path.exists(TICKERS_PATH):
        print(f"No ticker list found at {TICKERS_PATH}")
        print("Run: python data/build_ticker_list.py")
        sys.exit(1)

    with open(TICKERS_PATH) as f:
        all_tickers = json.load(f)

    # Allow filtering to specific tickers via CLI args
    if len(sys.argv) > 1:
        requested = set(sys.argv[1:])
        all_tickers = [t for t in all_tickers if t in requested]
        print(f"Filtering to {len(all_tickers)} requested tickers")

    conn = psycopg2.connect(DATABASE_URL)
    last_dates = get_last_dates(conn)

    # Split into full downloads vs incremental updates
    full_download = []
    incremental = {}  # ticker -> start_date

    today = datetime.now().date()

    for ticker in all_tickers:
        if ticker not in last_dates:
            full_download.append(ticker)
        else:
            last = last_dates[ticker]
            # Only update if last date is before today
            if last < today:
                start = last + timedelta(days=1)
                incremental[ticker] = str(start)

    print(f"{len(last_dates)} tickers in DB")
    print(f"{len(full_download)} new tickers to download (full history)")
    print(f"{len(incremental)} tickers to update (incremental)")
    print()

    failed = []
    total_rows = 0

    # ── Full downloads ───────────────────────────────────────
    if full_download:
        print("=== Full downloads ===\n")
        batches = [full_download[i:i + BATCH_SIZE] for i in range(0, len(full_download), BATCH_SIZE)]

        for batch_num, batch in enumerate(batches, 1):
            print(f"Batch {batch_num}/{len(batches)} — {len(batch)} tickers...")

            try:
                df = download_batch(batch)
            except Exception as e:
                print(f"  Batch failed: {e}")
                failed.extend(batch)
                continue

            batch_rows = 0
            for ticker in batch:
                try:
                    ticker_df = extract_ticker_df(df, ticker, len(batch))
                    if ticker_df.empty:
                        failed.append(ticker)
                        continue
                    insert_rows(conn, ticker_df)
                    batch_rows += len(ticker_df)
                except Exception as e:
                    print(f"  Failed {ticker}: {e}")
                    failed.append(ticker)
                    conn.rollback()

            total_rows += batch_rows
            print(f"  +{batch_rows:,} rows (total: {total_rows:,})")

            if batch_num < len(batches):
                time.sleep(DELAY_BETWEEN_BATCHES)

    # ── Incremental updates ──────────────────────────────────
    if incremental:
        print("\n=== Incremental updates ===\n")

        # Group tickers by start date so we can batch efficiently
        # Most will share the same "last date" so this batches well
        by_date: dict[str, list[str]] = {}
        for ticker, start in incremental.items():
            by_date.setdefault(start, []).append(ticker)

        for start_date, tickers in by_date.items():
            batches = [tickers[i:i + BATCH_SIZE] for i in range(0, len(tickers), BATCH_SIZE)]

            for batch_num, batch in enumerate(batches, 1):
                print(f"Updating {len(batch)} tickers from {start_date}...")

                try:
                    df = download_batch(batch, start=start_date)
                except Exception as e:
                    print(f"  Batch failed: {e}")
                    failed.extend(batch)
                    continue

                if df.empty:
                    print("  No new data")
                    continue

                batch_rows = 0
                for ticker in batch:
                    try:
                        ticker_df = extract_ticker_df(df, ticker, len(batch))
                        if ticker_df.empty:
                            continue
                        insert_rows(conn, ticker_df)
                        batch_rows += len(ticker_df)
                    except Exception as e:
                        print(f"  Failed {ticker}: {e}")
                        failed.append(ticker)
                        conn.rollback()

                total_rows += batch_rows
                print(f"  +{batch_rows:,} rows (total: {total_rows:,})")

                time.sleep(DELAY_BETWEEN_BATCHES)

    conn.close()

    if failed:
        unique_failed = sorted(set(failed))
        with open(FAILED_LOG, "w") as f:
            json.dump(unique_failed, f, indent=2)
        print(f"\n{len(unique_failed)} tickers failed — saved to {FAILED_LOG}")

    print(f"\nDone. Inserted {total_rows:,} total rows.")


if __name__ == "__main__":
    seed()
